### ISSUE TITLE
Peer Review 

### ISSUE THREAD

**Issue by subu250** [palmerlarson/IndieProject#3]
<h2 id="project" style="box-sizing: inherit; font-weight: 300; letter-spacing: -0.01em; font-size: 1.5625em; line-height: 1.4; margin: 1.6em 0px 0.64em; color: rgba(0, 0, 0, 0.87); font-family: Roboto, -apple-system, &quot;system-ui&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Project: Wealth & Debt Evaluator (WDev)
</h2><h3 id="developer" style="box-sizing: inherit; font-size: 1.25em; font-weight: 400; letter-spacing: -0.01em; line-height: 1.5; margin: 0.8em 0px; color: rgba(0, 0, 0, 0.87); font-family: Roboto, -apple-system, &quot;system-ui&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Developer: Palmer Larson</h3><h3 id="reviewer"  style="box-sizing: inherit; font-size: 1.25em; font-weight: 400; letter-spacing: -0.01em; line-height: 1.5; margin: 1.6em 0px 0.8em; color: rgba(0, 0, 0, 0.87); font-family: Roboto, -apple-system, &quot;system-ui&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Reviewer: Subheksha Karki</h3><div class="md-typeset__scrollwrap" style="box-sizing: inherit; margin: 1em -0.8rem 0px; overflow-x: auto; touch-action: auto; color: rgba(0, 0, 0, 0.87); font-family: Roboto, -apple-system, &quot;system-ui&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="md-typeset__table" style="box-sizing: inherit; display: inline-block; margin-bottom: 0.5em; padding: 0px 0.8rem;">  

Item | Considerations | Comments/Suggestions
-- | -- | --
  |   | Reviewer comments and suggestions go here. Each item should have at least one "kudos" and two suggestions for improvement
Problem Statement | 1. Accurately describes project purpose2. Is professional and free of typos, slang, etc.3. Fully explains the problem and the solution4. Is understandable by the average person |  Project is described very well with user stories the purpose of the project is to allow the user to track and map their personal finances. It provides the user with a simplistic view and future tracking for users looking to log and calculate finances. This application is to provide the user with a personalized and simplified view of their financial situation. Problem Statement explained and easy to understand. Kudos to the work that it is very well described and and used of Trello board makes work more smooth. Suggestion is that work is in progress so that technologies may be used as described near future.
Design Documentation | 1. Navigation/flow through the application is logical and easy to use.2. The order in which values are displayed are logical and easy to understand/use3. The order in which the form fields entered are logical and easy to understand/use4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens |  Design Documentation feedback is that application flow is   very easy to understand with flow and designed and mention about the problem statement.
Data model/Database | 1. Everything on the screens and problem statement/flow is represented in the model2. There is at least one 1-to-many relationship.3. The model represents good database design |  Problem statement/ flow is represented in the model. One to Many relationship and db design is in progress.
Code | 1. Proper Maven project structure is used2. a .gitignore file for IntelliJ Java projects has been implemented3. There is not any redundant or copy/paste code in the JSPs or classes4. Classes are appropriately-sized (no monster classes)Property files are used appropriately: no hard-coded values5. Logging statements are used rather than System.out.println and printStackTrace.6. There are appropriate unit tests/code coverage. | Maven Project structure is used in IntelliJ with JSPs, classes and there is no redundant or copy/paste code. Appropriate classes are used. Logging statements used in code is in progress.

</div></div>

**Comment by palmerlarson** [comment]
Hey @subu250 
This is very helpful! Thank you for reviewing my project!!
