### ISSUE TITLE
Checkpoint #2

### ISSUE THREAD

**Issue by palmerlarson** [palmerlarson/IndieProject#5]
Hi @pawaitemadisoncollege 

Checkpoint 2 is ready for review!

Thanks!

**Comment by pawaitemadisoncollege** [comment]
Hi @palmerlarson! Checkpoint 2 is looking good! 

Just one thing: 

- [x] Do you have an ERD for the current database? I'm looking for the tables, columns and relationships between the columns. You can produce this right in IntelliJ: https://www.jetbrains.com/help/idea/creating-diagrams.html. If I overlooked this, let me know!

**Comment by palmerlarson** [comment]
Hi! @pawaitemadisoncollege 

Sorry, I must have missed this! I added the diagram [here.](https://github.com/palmerlarson/IndieProject/blob/master/DatabaseDesign/ERD_screenshot.png)

**Comment by pawaitemadisoncollege** [comment]
Thanks @palmerlarson. One small thing - hibernate will require that each table has a unique id. It's likely easiest to just name that column `id`, just like you did on the user table. Otherwise, looks good!
