### ISSUE TITLE
Checkpoint #3

### ISSUE THREAD

**Issue by palmerlarson** [palmerlarson/IndieProject#6]
Hey @pawaitemadisoncollege! I think I'm ready for checkpoint 3 review.

Sorry for the delayed submission. I've hit some personal blockers recently that have caused delays, I can explain in more detail via slack if needed!

I've also hit some blockers on this project, though I am gaining a lot of ground and learning a lot through the trouble shooting process. My main issue right now is correlating cognito user attributes with my local database as well as authenticating users/importing user data locally. I don't fully understand the token system and how to authenticate users per servlet. Is it ideal to authenticate users per each servlet, or simply to only authenticate them upon login?

I appreciate all the help!

**Comment by pawaitemadisoncollege** [comment]
Hey @palmerlarson! 

That is a great question about cognito and auth in your application. I think this works for most situations:  

1. User logs in using the log in link/button your site.  
2. After the log in is successful, your application will receive the logged in user info. In the exercise we simply wrote out their user name to the screen at this point. 
3. I recommend checking if the user in your database (check by username). 
4. If they are in the db, put the user object in the http session, so you have easy access to the user info whenever you need it. If you have a user in the session, you know they've logged in successfully. 
5. If they are not in the db, add them using the cognito username and then proceed as in step 4 above.

Let me know if that helps! 

Regarding the checkpoint, can you share the url to your deployed application so I can verify the checkpoint? I looked for it here: https://github.com/mad-ent-java-s22/student/blob/main/IndividualProjects.md, but doesn't look to be listed there yet. Thanks!

Regarding personal blockers - please let me know if there is anything you feel I should know and if there is anything at all that I can do to help!

**Comment by palmerlarson** [comment]
Hey @pawaitemadisoncollege ,
Thanks for this! I added (http://indieproject-env.eba-rqviw5bv.us-east-2.elasticbeanstalk.com/index.jsp) to the student repo.

**Comment by pawaitemadisoncollege** [comment]
Thanks @palmerlarson 

Sign up and Sign in capability look good for checkpoint 3.  

- [x] Is there a place that I can see that data is getting returned from the database out on the aws deployed version?

**Comment by palmerlarson** [comment]
Achieved singular authentication > open session > logout > close session
